# Use official nginx image
FROM nginx:stable-alpine

# Copy your dist folder to nginx html directory
COPY dist/ /usr/share/nginx/html

# Copy nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy SSL certificates
COPY certs/ /etc/nginx/certs/

EXPOSE 80 443
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
